# Example/schema for the FirePRD workflow state file.
#
# Runtime note:
#   This file is NOT used directly by the workflow. At runtime, the
#   `*start` command (see tasks/initialize-workflow.md) generates
#   `fireprd/cache/workflow-state.toml` for the active project.
#
# Usage:
#   - Use this file as a reference for expected fields and types.
#   - Do not commit runtime state under fireprd/cache/ in your projects.

# The version of the state file schema.
version = "1.0"

# The current stage of the workflow.
# Possible values:
#   - "NOT_STARTED"
#   - "PLAN_CREATED"
#   - "ANALYSIS_COMPLETE"
#   - "TOC_APPROVED"
#   - "CONTENT_PLAN_COMPLETE"
#   - "PLAN_FINALIZED"
#   - "GENERATION_COMPLETE"
status = "PLAN_CREATED"

# The root path to the source code being analyzed.
sourcePath = "."

# The semantic command for the next logical step.
nextStep = "analyze"

# File paths to the intermediate documents generated during the workflow.
# Note: TOML doesn't have null, so we use empty strings "" to indicate unset values.
# Tasks should check: if value == "" then treat as not yet generated.
[artifacts]
codeAnalysis = ""
toc = ""
contentPlan = ""

# The user-approved plan for the final document.
[plan]
# The final, approved Table of Contents structure.
# Array of Part objects (see type definition below)
toc = []

# A queue of generation jobs, populated after the plan is finalized.
# Enables sequential and concurrent generation.
# Array of GenerationJob objects (see type definition below)
generationQueue = []

# User-configurable settings that affect downstream tasks.
[settings]
# Max files per feature before a chapter is marked for splitting in finalize-plan.
# Integer; typical range 3-10; default 5.
splitThreshold = 5

# --- Types (informal documentation) ---
#
# Part:
#   id = "String"            # unique identifier for a chapter/section
#   title = "String"
#   summary = "String"       # brief summary shown in finalize-plan
#   children = []            # optional nested sections (depth limited by rules)
#
# GenerationJob:
#   id = "String"           # unique job id (e.g., chapter or subsection)
#   title = "String"
#   [input]                 # references to artifacts used to generate
#     featureId = "String"  # id from analysis linking to this chapter
#   outputFile = "String"   # path for the generated markdown file
#   status = "String"       # "pending" | "running" | "done" | "failed"

# --- Example (illustrative only; not executed) ---
# Uncomment to see a realistic state at PLAN_FINALIZED stage:
#
# version = "1.0"
# status = "PLAN_FINALIZED"
# sourcePath = "."
# nextStep = "generate-all-chapters"
#
# [artifacts]
# codeAnalysis = "fireprd/cache/code-analysis.md"
# toc = "fireprd/cache/toc.md"
# contentPlan = "fireprd/cache/content-plan.md"
#
# [[plan.toc]]
# id = "feat-auth"
# title = "Authentication"
# summary = "User login and session management."
# children = []
#
# [[plan.generationQueue]]
# id = "job-auth"
# title = "Authentication"
# outputFile = "docs/chapters/authentication.md"
# status = "pending"
#
# [plan.generationQueue.input]
# featureId = "feat-auth"
#
# [settings]
# splitThreshold = 5
